spring.application.name=port-db
# For development: recreate schema on each start so we don't have to manually drop tables.
# Options: 'create' - create schema, 'create-drop' - create and drop on shutdown.
# Use 'create' to always rebuild DB on startup.
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/port-db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
navigation.api.url=http://localhost:8081/api/route
